# Generated by Django 2.0.1 on 2019-02-11 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depcode', models.CharField(max_length=250)),
                ('depdescription', models.CharField(max_length=250)),
                ('store_depflag', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=10)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-depcode',),
            },
        ),
        migrations.CreateModel(
            name='Financialyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fafromdate', models.DateField(default=datetime.date.today)),
                ('fatodate', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-fafromdate',),
            },
        ),
    ]
