# Generated by Django 2.0.1 on 2019-02-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulbstoremain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliercode', models.CharField(max_length=10)),
                ('suppliername', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('suppliername',),
            },
        ),
    ]
