# Generated by Django 2.0.1 on 2019-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulbstoremain', '0002_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cstno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactvie')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplieraddress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplieremailid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='suppliermobileno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='suppliertelephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tinno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vatno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
