# Generated by Django 2.0.1 on 2019-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulbstoremain', '0003_auto_20190224_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplieraddress',
            field=models.TextField(),
        ),
    ]
