# Generated by Django 2.0.1 on 2019-02-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulbstoremain', '0004_auto_20190224_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplieremailid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='e-mail'),
        ),
    ]
