# Generated by Django 2.0.1 on 2019-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulbstoremain', '0005_auto_20190224_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cstno',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CST No'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplieraddress',
            field=models.TextField(verbose_name='Suplier Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliercode',
            field=models.CharField(max_length=10, verbose_name='Supplier Code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplieremailid',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliermobileno',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliername',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suplier Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliertelephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Suplier Telephone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tinno',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tin No.'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vatno',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='VAT No'),
        ),
    ]
